<% require "uri" %>

db_config: &db_config
  <% if ENV["DATABASE_URL"].present? %>
  <%uri = URI.parse(ENV[ "DATABASE_URL" ]) if ENV["DATABASE_URL"].present? %> 
  ursername: <%= uri.user %> 
  password: <%= uri.password %> 
  host: <%= uri.host %> 
  <% else %> 
  host: root
  password: ''
  host: localhost
  <% end %> 
  adapter: mysql2 
  pool: 10 
  timeout: 5000 
  port: 3306 

development: 
  <<: *db_config
  database: rails_test_api
  username: root
  password: '12345678'
